devices: 0

model:
  name: 'NightToday'
  names_domains: ['Day', 'Thermal', 'Night']
  mode: 'train'  # 'train', 'test'
  build_from_checkpoint: True
  fusion_first: True

  seg:
    num_classes: 19
    type: 'LETNet'#  'LETNet'  # 'Segmentor'
    base_dim: 64
    n_layers: 4
    training_schedule:
      start_epoch: 0
      end_epoch: 75
      updateGT_D_start_epoch: 5
      updateGT_TN_start_epoch: 15

  gen:
    downscaling: 2
    input_size: 512
    hidden_dim: 384
    n_enc_layers: 4
    n_shared_layers: 2
    n_dec_layers: 5
    dropout: 0.0
    fus:
      preprocess_thermal:
        bins: 2048
        scene: 1
      hidden_dim: 256
      n_enc_layers: 4
      dropout: 0.25
      n_downscaling: 2
      type: IAware  # 'IAware' # 'UResNet'

  discr:
    base_dim: 64
    n_layers: 4

training:
  checkpoint_dir: '/checkpoints'
  checkpoint_freq: 1  # epochs
  checkpoint_save_latest: 500  # steps
  pedestrian_color: #[red, black] #[black, red] # color of pedestrian in fake D images (color, contour)
  split_optimizers: False
  split_weights: False
  visualize_freq: 25  # steps
  visualize_dir: '/training_visuals'
  test_freq: 0  # epochs
  start_epoch: 75
  total_epochs: 100
  resume: True
  resume_epoch: latest
#    G2: 100
#    G3: 100
#    D: 100
#    S: 100
  partial_train:
#    G: [2, 5, 6]
#    D: [2]
#    S: [2]
  lr:
    G: 0.0001
    D: 0.0001
    S: 0.0001
  betas:
    G: [0.5, 0.999]
    D: [0.5, 0.999]
    S: [0.5, 0.999]
  loss_scheduler:  # [switch, switch, switch, ...], value
    lambda_color: [[ 20,  ], 3.0]
    lambda_color_day: [[ 20,  ], 5]
    lambda_id: [[ 0, 2 ], 0.1]
    lambda_cycle:  [[ 0,  ], 5.0]
    lambda_ssim:  [[ 0,  ], 2.5]
    lambda_seg:  [[ 1, ], 1.0]
    lambda_semEdge:  [[ 1,  ], .5]
    lambda_gan:  [[ 0,  ], 1.0]
    lambda_tv:  [[ 1,  ], 5.0]
    lambda_sga: [[ 40,  ], 1.0]
    lambda_latent: [[ 0, 1], 0.1]
    lambda_att: [[ 40, ], 0.] # 1.0
    lambda_fus: [[ 0,  2], 5.0]
    lambda_scale_robustness: [[ 75,  ], 1.0] # 1.0
    lambda_trafficlight: [[ 10,  ], 0.2] # 0.2
    lambda_illumination_aware: [[ 0,  ], 1.0]
    lambda_thermal: [[ 1,  ], 2.0]
    lambda_contour: [[ 20,  ], 2.0]
    lambda_sharpness: [[ 0,  ], 25.0]
    lambda_cgr: [[ 5, ], 3.5]  # Conditional Gradient Repair
    lambda_bc: [[ 5, ], 2.0]  # Bias correction Loss
  gan_type: "lsgan"  # ['lsgan', 'hinge', 'wgan-gp', 'ralsgan']

data:
  loader:
    batch_size: 1
    num_workers: 1
    shuffle: True
    resize_and_crop: True
  train_datasets:
    - name: 'FLIR'
      sampling: 1
      augmentations:
        hflip: True
    - name: 'LYNRED'
      sampling: 1
      augmentations:
        hflip: True
#  test_datasets:
#      - name: 'LYNRED_DAY_SAMPLES'
#        sampling: 1
#        augmentations:
#          hflip: False
#      - name: 'LYNRED_NIGHT_SAMPLES'
#        sampling: 1
#        augmentations:
#          hflip: False


