devices: 0

model:
  name: 'NightToday'
  names_domains: ['Day', 'Thermal', 'Night']
  mode: 'train'  # 'train', 'test'
  build_from_checkpoint: False
  fusion_first: True
  pedestrian_color: red
  seg:
    num_classes: 19
    type: 'LETNet'  # 'Segmentor'
    base_dim: 64
    n_layers: 4
    training_schedule:
      start_epoch: 5
      end_epoch: 75
      updateGT_D_start_epoch: 20
      updateGT_TN_start_epoch: 30

  gen:
    type: ResNet # ViT, ResNet
    downscaling: 2
    ViT_model: dinov3_vits16  #  dinov3_convnext_tiny, dinov3_vits16
    # common
    input_size: 256
    hidden_dim: 384
    n_enc_layers: 4
    n_shared_layers: 2
    n_dec_layers: 5
    dropout: 0.0
  discr:
    base_dim: 64
    n_layers: 4

training:
  checkpoint_dir: '/checkpoints'
  checkpoint_freq: 1  # epochs
  checkpoint_save_latest: 500  # steps
  split_optimizers: False
  split_weights: False
  visualize_freq: 25  # steps
  visualize_dir: '/training_visuals'
  test_freq: 1  # epochs
  start_epoch: 41
  total_epochs: 100
  resume: True
  resume_epoch: latest
#    G: -1
#    G2: 100
#    G3: 100
#    D: 100
#    S: 100
  partial_train:
#    G: [2, 5, 6]
#    D: [2]
#    S: [2]
  lr:
    G: 0.0002
    D: 0.0002
    S: 0.0002
  betas:
    G: [0.5, 0.999]
    D: [0.5, 0.999]
    S: [0.5, 0.999]
  loss_scheduler:  # [switch, switch, switch, ...], value
    lambda_color: [[ 0,  ], 10.0]
    lambda_id: [[ 0,  ], 1.0]
    lambda_cycle:  [[ 0,  ], 5.]
    lambda_ssim:  [[ 0,  ], 2.5]
    lambda_seg:  [[ 2], 2.5]
    lambda_semEdge:  [[ 0,  ], 1.5]
    lambda_gan:  [[ 0,  ], 1.0]
    lambda_tv:  [[ 0,  ], 2.5]
    lambda_sga: [[ 0,  ], 0.5]
    lambda_latent: [[ 0,  ], 2.0]
    lambda_att: [[ 0,  30], 2.0]
    lambda_acl: [[ 0,  ], 1.0]
    lambda_scale_robustness: [[ 0,  ], 0.5]
    lambda_mean_var: [[ 0,  ], 1.0]
    lambda_milo: [[ 0,  ], 1.0]
    lambda_thermal: [[ 0,  ], 0.5]
    lambda_sharpness: [[ 0,  ], 25.0]
    lambda_cgr: [[ 0,  ], 1.0]  # Conditional Gradient Repair
  gan_type: "lsgan"  # ['lsgan', 'hinge', 'wgan-gp', 'ralsgan']

data:
  loader:
    batch_size: 1
    num_workers: 1
    shuffle: True
    resize_and_crop: True
  datasets:
    - name: 'FLIR'
      sampling: 1
      augmentations:
        hflip: True
#    - name: 'LYNRED'
#      sampling: 1
#      augmentations:
#        hflip: True
#    - name: 'Lynred_reg'
#      sampling: 0.5
#      augmentations:
#        hflip: True

